---
- name: Launch HTTP proxy with load balancing
  community.docker.docker_container:
    name: "{{ proxy_name }}"
    image: "{{ proxy_image_lb }}"
    pull: yes
    restart_policy: unless-stopped
    published_ports:
      - "{{ proxy_port }}:80"
    networks:
      - name: "{{ front_network }}"
        aliases:
          - "{{ proxy_name }}"
    state: started
    depends_on:
      - "{{ app_name }}-blue"
      - "{{ app_name }}-green"
