name: CI devops 2025

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show tool versions
        run: |
          java -version
          mvn -v
          docker --version

      - name: Build and test with Maven
        run: |
          cd simpleapi
          mvn -B -ntp clean verify
    
