# CI/CD Pipeline pour le projet 3-tier architecture
# Ce workflow automatise les tests et la validation du code backend
name: CI devops 2025

# Déclenchement du pipeline sur les événements suivants :
# - Push sur les branches master et develop
# - Pull requests vers master et develop
on:
  push:
    branches:
      - master      # Branche principale de production
      - develop     # Branche de développement
  pull_request:
    branches:
      - master      # Validation des PR vers master
      - develop     # Validation des PR vers develop

jobs:
  # Job de test du backend Spring Boot
  test-backend:
    runs-on: ubuntu-24.04  # Utilisation de la dernière version LTS d'Ubuntu

    steps:
      # Étape 1 : Récupération du code source depuis le repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Version stable et rapide

      # Étape 2 : Configuration de l'environnement Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin    # Distribution Eclipse Temurin (OpenJDK)
          java-version: '21'       # Version Java 21 (LTS)
          cache: maven            # Cache Maven pour accélérer les builds

      # Étape 3 : Affichage des versions des outils pour debugging
      - name: Show tool versions
        run: |
          java -version    # Vérification de la version Java
          mvn -v          # Vérification de la version Maven
          docker --version # Vérification de Docker (pour les tests d'intégration)

      # Étape 4 : Build et tests Maven
      # -B : mode batch (non-interactif)
      # -ntp : no transfer progress (réduction des logs)
      # clean : nettoyage des artefacts précédents
      # verify : exécution des tests unitaires et d'intégration
      - name: Build and test with Maven
        run: |
          cd simpleapi    # Navigation vers le dossier contenant le pom.xml
          mvn -B -ntp clean verify
    
