name: CI devops 2025

# configuration des déclencheurs du pipeline
on:
  push:
    branches:
      - master    
      - develop   
  pull_request:
    branches:
      - master   
      - develop   

jobs:
  # test du backend Spring Boot
  test-backend:
    runs-on: ubuntu-24.04  

    steps:
      # récupération du code source depuis le repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # configuration de l'environnement Java avec Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin   
          java-version: '21'        
          cache: maven            

      # affichage des versions des outils pour debugging
      - name: Show tool versions
        run: |
          java -version
          mvn -v
          docker --version

      #build et exécution des tests avec Maven

      - name: Build and test with Maven
        run: |
          cd simpleapi  # le pom.xml est dans ce dossier
          mvn -B -ntp clean verify
    
